language: php
dist: trusty
cache:
  npm: true
  directories:
  - "~/.cache"
php:
- 5.5
node_js:
- 10
addons:
  chrome: stable
before_install:
- npm install -g npm@5.5.1
before_script:
- npm install -g grunt-cli
- npm install
- mkdir -p dist/js
- gem update --system && gem install scss_lint
install:
- composer self-update
- composer install --prefer-dist --no-interaction
script:
- phpunit
- grunt build
- npm test
- npm run coverage
- "$(npm bin)/cypress run --record --key 91a66ab2-562b-47ba-93e3-aee77725f748"
after_success:
- grunt deploy
- bash <(curl -s https://codecov.io/bash)
sudo: required
deploy:
  provider: releases
  api_key:
    secure: q/5L4w87ve2sbEgQOLqIHGrXqBBTV7hCFg8koh+RjovnBl/z6ZDucQMmI5SAf1GEVzh30XXhYvVnpO6DQ0vJw99TESiIFyECW45lswHzW40bZ9jqgm969Xtrw97ifdZLWMmRxQp9q/OgYejPA1UpYLKNJTWJ9ddcl9BTWPRImdYAM//mVbImp7GnKWZlX1MLow443J4d/uWeW9kOmqUCp5gTmGJGHe4inTq+ooFuL5ceSaq26J7yAvQuzP1BYdwSV7yphVrP+jmfd3enayxQJrozcZ618bHscYy1Fa6r3ruM1s9vR7FQ5vDmR9SiEpikjDQ8TqCI5z64LI9x0MGB81ivb8o3z+hD7lFacSqUNjoBvytKAEKVc+//8EvQU07Rlw2N0yp31aBfByZyH5ZKQ4NkmLdMeeLrzo+FmlFX/3g7M0ah2X9TJJ4Qr1h7XTOyuqrVwx67AbSCXdg8+45+M+VONIy9+Yjj9NCwvNEtDbNCU/F0Hfb+0cX2YdCjY6eDmIGRUEylxj7OUrcZQ88vYZow6WidCEfNQTaqsn6cL+wg1gPT/KjxkL2c7YMHVRO64AADa0ppMBqgza1EWpRXsmuhCQSF2pkOeX7aqJ3CR5YEJYCZ4dn94aSyeBipny5DH1MWgeP3hAKf32iOtuGk0wFN/nllTqASLK3nrg6nmPU=
  file: pulsar.zip
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
env:
  global:
    secure: vw722pnA32erJjweWTAJcSlEd1LFrYF9diDeLhupPH0clb36zvXALPiG+W9uzGHx8v/LN980UoNsp5JADg/uipPPLwfQ0vEjG+QXFxW2zm/d5qcK5o/oDcLd9XQFzvQB5Y0VeDTWKAK0Yn4ac845/v7b32EUT8khVLdNNUVOHDQQrpI6sbfMVTjNnc0DJwyYD6I01VVi6MlDLGs8pKyQTl0mXFn8kXR/1TfzqEbRHFfROXQ4Ps53ilJh7MRwa/cna+n26tEmTToxD3qvp4igqBSL0HXE/w7BylJlT9gTZFAS0/6YzlG6VqY2jqM/5rG6Aw/1iMUAqQc4G6bJD29GNvfRyLlIvzC3zZRq10wlFbuEHvgnOrB8SqKTRqA7njwdBpJ05/BEGwdX1mymjNMhMhOD7261OrzORNi9jwZ/UHXjkkP6cq1kHdLEMapPF3G3e7S1V2if9x+lxYEhFaqeVWFD+0rdxPruXE3kTrp/Zx0DIm8tjG6pCwNK3ZBjcv6uzwmlw0QA1yT45CdedSM3S0V6zEjDTqg22aiexr/sxG8kxgEaPUm311AkhJhQvTZhzH+oc+5CAzFGDjDDIchb9n8qn17QanV+QnUX9++IQNxWptNpS7gxwQLUh9ww7iHEanTFajwSIo1mlTmUTVfjEJavujH76hSgiUT+BYlIyM8=
