version: '2'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      secrets:
        - npmrc
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html/:cached
    ports:
      - 9000:80
secrets:
  npmrc:
    file: ~/.npmrc