version: '2'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      secrets:
        -
    working_dir: /var/www/html
    ports:
      - 9000:80
secrets:
  npmrc:
    file: ~/.npmrc