version: '2'
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        working_dir: /var/www/html
        volumes:
          - ./:/var/www/html/:cached
        ports:
          - 9000:80
        environment:
          - APACHE_DOCUMENT_ROOT=/var/www/html