name: Docusaurus
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - uses: redkubes/docusaurus-deploy-action@v1
        with:
          source-folder: docs
          git-user: stanton
          git-password: ${{ secrets.GITHUB_TOKEN }}
          deployment-branch: gh-pages
