name: Deploy Documentation

on:
  push:
    branches: [develop]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publish:
    name: Build and Deploy Docs
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      # Node is required for npm
      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'
          cache-dependency-path: 'docs/package-lock.json'
      # Install and build Docusaurus website
      - name: Build documentation
        working-directory: docs
        run: |
          echo "::group::Documentation Build Process"
          echo "Installing dependencies..."
          npm ci
          echo "Building documentation site..."
          npm run build
          echo "::endgroup::"
      - name: Deploy to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build
          publish_branch: gh-pages
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          full_commit_message: 'docs: update documentation site from commit ${{ github.sha }}'