# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Run JS test suite

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
       matrix:
         node-version: [18, 20]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    # The local testing-friendly version of the FontAwesome token check
    - name: Setup FontAwesome if token exists
      if: env.FONTAWESOME_TOKEN != ''
      run: npm config set '//npm.fontawesome.com/:_authToken' "${{ env.FONTAWESOME_TOKEN }}"
      env:
        FONTAWESOME_TOKEN: ${{ secrets.FONTAWESOME_TOKEN }}
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build
      run: npm run build --if-present
    
    # Configure Chrome for headless testing in containers
    - name: Configure Chrome sandbox
      run: |
        # Create required directories
        sudo mkdir -p /var/lib/chrome-sandbox
        # Set permissions
        sudo chown root:root /var/lib/chrome-sandbox
        # Apply proper permissions
        sudo chmod 4755 /var/lib/chrome-sandbox
    
    - name: Test
      run: npm test
      env:
        CHROME_BIN: chromium-browser
        # Allow running Chrome without sandbox in CI environment
        CHROMIUM_FLAGS: "--no-sandbox --disable-setuid-sandbox --disable-dev-shm-usage --disable-accelerated-2d-canvas --no-first-run --no-zygote --disable-gpu"
        # Additional environment variables for Puppeteer/Chrome
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
        PUPPETEER_EXECUTABLE_PATH: "/usr/bin/chromium-browser"
