# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Run JS test suite

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: Node.js ${{ matrix.node-version }} Test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    strategy:
      fail-fast: false
      matrix:
        node-version: [18, 20]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        
    - name: Setup Node.js ${{ matrix.node-version }}
      id: setup-node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Setup FontAwesome credentials
      if: env.FONTAWESOME_TOKEN != ''
      run: npm config set '//npm.fontawesome.com/:_authToken' "${{ secrets.FONTAWESOME_TOKEN }}"
      env:
        FONTAWESOME_TOKEN: ${{ secrets.FONTAWESOME_TOKEN }}
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build
      run: npm run build --if-present
    
    - name: Configure Chrome for headless testing
      run: |
        echo "::group::Chrome Sandbox Configuration"
        echo "Setting up Chrome sandbox for containerized tests"
        sudo mkdir -p /var/lib/chrome-sandbox
        sudo chown root:root /var/lib/chrome-sandbox
        sudo chmod 4755 /var/lib/chrome-sandbox
        echo "::endgroup::"
    
    - name: Run tests
      run: npm test
      env:
        CHROME_BIN: chromium-browser
        CHROMIUM_FLAGS: "--no-sandbox --disable-setuid-sandbox --disable-dev-shm-usage --disable-accelerated-2d-canvas --no-first-run --no-zygote --disable-gpu"
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
        PUPPETEER_EXECUTABLE_PATH: "/usr/bin/chromium-browser"
        
    - name: Upload test artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: js-test-results-node-${{ matrix.node-version }}
        path: |
          ./coverage/
          ./tests/js/web/index.html
        if-no-files-found: ignore
        retention-days: 7
