# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Run JS test suite

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: Node.js ${{ matrix.node-version }} Test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    strategy:
      fail-fast: false
      matrix:
        node-version: [18, 20]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        
    - name: Setup Node.js ${{ matrix.node-version }}
      id: setup-node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Setup FontAwesome credentials
      if: env.FONTAWESOME_TOKEN != ''
      run: npm config set '//npm.fontawesome.com/:_authToken' "${{ secrets.FONTAWESOME_TOKEN }}"
      env:
        FONTAWESOME_TOKEN: ${{ secrets.FONTAWESOME_TOKEN }}
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build
      run: npm run build --if-present
    
    - name: Create Chrome wrapper
      run: |
        # Install Chrome
        sudo apt update
        sudo apt install -y google-chrome-stable xvfb

        # Create wrapper script that forces no-sandbox
        sudo tee /usr/local/bin/chrome-for-tests <<-'CHROME'
        #!/bin/bash
        # This script will be used instead of the actual Chrome binary
        # It passes the --no-sandbox flag to Chrome regardless of how it's called
        exec /usr/bin/google-chrome --no-sandbox --disable-setuid-sandbox --disable-dev-shm-usage "$@"
        CHROME
        
        # Make executable
        sudo chmod +x /usr/local/bin/chrome-for-tests
        
        # Link as 'google-chrome' in a directory that takes precedence in PATH
        mkdir -p $HOME/bin
        ln -s /usr/local/bin/chrome-for-tests $HOME/bin/google-chrome
        echo "$HOME/bin" >> $GITHUB_PATH
        
    - name: Run tests
      run: xvfb-run -a npm run test:ci
      env:
        NODE_OPTIONS: "--max-old-space-size=4096"
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
      
    - name: Upload test artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: js-test-results-node-${{ matrix.node-version }}
        path: |
          ./coverage/
          ./tests/js/web/index.html
        if-no-files-found: ignore
        retention-days: 7
