name: Test PHP 8.4 Compatibility

on:
  # Manual trigger
  workflow_dispatch:
  # Run weekly to catch changes in PHP 8.4 development
  schedule:
    - cron: '0 0 * * 1' # Run every Monday at midnight

permissions:
  contents: read

jobs:
  php-compatibility:
    name: PHP 8.4 Compatibility Test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Setup PHP 8.4
      id: setup-php
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'
        extensions: mbstring, intl, zip
        coverage: none
        tools: composer:v2
        ini-values: memory_limit=256M
      env:
        update: true # Ensure we get the latest development build

    - name: Display PHP information
      run: |
        echo "::group::PHP Environment Details"
        php -v
        php -m
        composer --version
        echo "::endgroup::"

    - name: Validate composer files
      run: composer validate --strict

    - name: Get Composer cache directory
      id: composer-cache
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - name: Setup Composer cache
      uses: actions/cache@v4
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-php-8.4-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-8.4-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --ignore-platform-reqs

    - name: Check syntax compatibility
      run: |
        echo "::group::PHP Syntax Validation"
        find src -type f -name "*.php" -print0 | xargs -0 -n1 php -l
        echo "::endgroup::"

    - name: Run PHPUnit tests (if available)
      id: phpunit
      continue-on-error: true
      run: |
        if [ -f "./vendor/bin/phpunit" ]; then
          echo "::group::PHPUnit Tests"
          PHP_VERSION=$(php -r 'echo PHP_VERSION;')
          echo "Testing with PHP $PHP_VERSION"
          ./vendor/bin/phpunit --configuration phpunit.xml.dist || echo "Tests failed but this is expected with development PHP"
          echo "::endgroup::"
          echo "run=true" >> $GITHUB_OUTPUT
        else
          echo "PHPUnit not found in vendor directory"
          echo "run=false" >> $GITHUB_OUTPUT
        fi
      
    - name: Run static analysis (if available)
      continue-on-error: true
      run: |
        if [ -f "./vendor/bin/phpstan" ]; then
          echo "::group::Static Analysis"
          ./vendor/bin/phpstan analyse --level=0 src
          echo "::endgroup::"
        else  
          echo "PHPStan not installed"
        fi

    - name: Upload test results
      if: always() && steps.phpunit.outputs.run == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: php-8.4-compatibility-results
        path: ./build/logs/
        if-no-files-found: ignore
        retention-days: 7 